describe('Los estudiantes login', function() {
    it('Visits los estudiantes and fails at login', function() {
        cy.visit('https://losestudiantes.co')
        cy.contains('Cerrar').click()
        cy.contains('Ingresar').click()
        cy.get('.cajaLogIn').find('input[name="correo"]').click().type("hd.tafur10@uniandes.edu.co")
        cy.get('.cajaLogIn').find('input[name="password"]').click().type("PruebasAutomatizadas")
        cy.get('.cajaLogIn').contains('Ingresar').click()
        cy.wait(3000)
        //cy.contains('El correo y la contraseña que ingresaste no figuran en la base de datos. Intenta de nuevo por favor.')
        cy.get('.Select-arrow').click().type("Luz Miriam")
        cy.contains('Luz Miriam Echeverry Navarro - Matemáticas').click()
        cy.wait(5000)
        cy.get('.tituloLosEstudiantes').click()
        cy.wait(1000)
        cy.get('.false').contains('Alfabético').click()
        cy.wait(2000)
        cy.get('.profesor').contains('Adolfo Jose Quiroz Salazar').click()
        cy.wait(2000)
        cy.get(':nth-child(2) > .labelHover > input.jsx-1802368871').click()
    })
})